export const PUBLIC_PATHS = {
  home: '/',
  about: '/about',
  conferences: '/conferences',
  conferenceDetails: (slug = ':slug') => `/conferences/${slug}`,
  reviews: '/reviews',
  contact: '/contact',
  terms: '/terms-and-conditions',
  privacy: '/privacy-policy',
} as const;

export const ADMIN_PATHS = {
  root: '/admin',
  login: '/admin/login',
  forgotPassword: '/admin/forgot-password',
  resetPassword: '/admin/reset-password',
  unauthorized: '/admin/403',
  dashboard: '/admin/dashboard',
  conferences: '/admin/conferences',
  conferenceNew: '/admin/conferences/new',
  conferenceEdit: (id = ':id') => `/admin/conferences/${id}/edit`,
  categories: '/admin/categories',
  speakers: '/admin/speakers',
  agenda: '/admin/agenda',
  sponsors: '/admin/sponsors',
  gallery: '/admin/gallery',
  reviews: '/admin/reviews',
  registrations: '/admin/registrations',
  abstracts: '/admin/abstracts',
  pages: '/admin/pages',
  media: '/admin/media',
  users: '/admin/users',
  settings: '/admin/settings',
} as const;
